### ISSUE TITLE
can not find the file in "torch.load('B0050.pth')"

### ISSUE THREAD

**Issue by wenzhilv** [BravoSun/NCCT-atlas-for-ASPECTS-scoring#1]
Hello author, I am doing research related to stroke and want to do a pre-processing with your code. But, I find that a weight file is missing when running the code, I hope you can tell me how to download this weight file, thank you!

**Comment by jiangliMED** [comment]
same question here...
Also is it possible to provide the 3D atlas? 
Thanks!

**Comment by BravoSun** [comment]
The weight file has been uploaded, and the ASPECTS atlas is a 2D atlas.
